function cost = cost_function(params)

  %%%
  % returns the log-likelihood that a given rate function generated a given spike train
  % the rate function is generated by convolving a known extrinsic biological signal
  % with an exponentially-modified Gaussian kernel

end % cost_function 
