% generate fake Poisson-distributed data based on a non-homogeneous rate parameter
% generate the non-homogeneous rate parameter by convolving a known signal
% with an exponentially-modified Gaussian kernel
%
% Arguments:
%   % raw_signal: a time-varying rate used to generate the Poisson-distributed spike train
%   % bandwidth: how long (in units of timesteps) the kernel is
%   % params: the parameters of the kernel to convolve with the raw_signal
%     the kernel is an exponentially-modified Gaussian with three parameters
%     mu, sigma, and tau
%
% Outputs:
%   spike_train: the spike-train generated by the Poisson process
%   transformed_signal: the rate used as a time-varying parameter of the Poisson process

function [spike_train, transformed_signal] = generate_fake_data(raw_signal, bandwidth, params)

end % function
